name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "2.1.4"

      - name: Install dependencies
        run: |
          poetry install --only main,docs

      - name: Build documentation
        run: |
          poetry run mkdocs build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site