name: Unit Testes

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  pytest:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12", "3.13","3.14"] 
        os: [windows-latest,windows-11-arm,macos-latest, ubuntu-latest,ubuntu-26.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --group test --group linter

      - name: Run all possible tests
        env:
          PYTHONIOENCODING: utf-8
        run: uv run task test-all

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
