name: Unit Testes

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  pytest:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10","3.11","3.12", "3.13","3.14"] 
        os: [windows-latest,windows-11-arm,macos-latest, ubuntu-latest,ubuntu-26.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name : Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "2.1.4"

      - name: Install dependencies
        run: poetry self add poethepoet@0.37 && poetry install --without docs --no-root

      - name: mypy
        env:
            PYTHONIOENCODING: utf-8
        run: poetry poe type-checking

      - name: Testing code with pytest
        env:
          PYTHONIOENCODING: utf-8
        run: poetry poe unit-tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
